### ISSUE TITLE
 Implement a resource management component

### ISSUE THREAD

**Issue by so-sahu** [ironcore-dev/libvirt-provider#170] opened 2024-02-09 10:31 UTC
# Summary

This issue captures the efforts to implement a resource management component and the corresponding reconciler changes. The proposals and changes can be discussed in this issue.

**Comment by hardikdr** [comment] 2024-02-21 09:32
Is this the dupe of https://github.com/ironcore-dev/libvirt-provider/issues/147 ? Can we close this one?

**Comment by lukas016** [comment] 2024-04-17 07:09
merged

**Closed by lukas016** 2024-04-17 07:09 UTC
Labels: enhancement, prio-high, dt-target
